# Generated by Django 5.2.10 on 2026-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_interviewsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
